name: noe
channels:
  - conda-forge
  - defaults
  - omnia
dependencies:
  - python=3.7.4
  - numpy
  - scipy
  - scikit-learn=0.20.0
  - rdkit
  - pip
  - openmm
  - mdtraj
  - tqdm
  - notebook
  - nglview
  - joblib
  - ase
  #mlddec
  #mdfptools
  # - pip: